import Foundation

public let loremIpsum = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse gravida nunc sapien. Duis vitae tincidunt nisl. Fusce vel elit purus. Nam volutpat lacus eget sem vestibulum, in varius est vestibulum. Maecenas ac massa in nulla luctus euismod sed nec felis. Donec nec metus fermentum, feugiat tellus sed, consectetur justo. Suspendisse potenti. Aenean pretium nulla elit, quis imperdiet enim pretium id. Donec interdum, libero quis maximus ullamcorper, odio est posuere nunc, eu varius ipsum velit non sem.

Fusce leo mauris, porta at urna eu, scelerisque porttitor magna. Vestibulum a ipsum vitae ipsum aliquet tincidunt. Suspendisse lacinia neque nec massa tincidunt, nec suscipit massa tempus. Cras blandit, arcu et vestibulum sollicitudin, dolor velit mollis velit, nec sodales ante urna nec mi. Nunc eget massa id sapien pretium accumsan. Phasellus rutrum libero ac laoreet lacinia. Aliquam iaculis tempus lacus, eget congue risus hendrerit vitae. Suspendisse et rutrum ipsum, vitae scelerisque ante. Phasellus euismod velit sit amet justo tincidunt feugiat. Mauris euismod lectus ut volutpat efficitur. Suspendisse vestibulum semper mollis. Curabitur et mi aliquet, condimentum enim at, interdum tortor. Morbi et massa vel nibh fringilla fringilla rhoncus ac eros. Nam neque mauris, congue a dolor in, venenatis euismod dolor. Duis nibh ipsum, molestie a vehicula non, convallis eget velit.

Proin porttitor mi tellus, id faucibus sem sollicitudin in. Sed eget luctus quam, eget tempor nibh. Aliquam condimentum, velit quis euismod vestibulum, dolor eros dictum lectus, at tempus massa mi sit amet nunc. Aenean eu nibh at tortor commodo malesuada. Maecenas ac eleifend augue. Nullam in sagittis arcu. Cras eu lacinia neque. Vivamus laoreet odio eget finibus consectetur. Aliquam erat volutpat. In sit amet pretium ipsum, a fringilla nunc. Nullam et elit sit amet augue dapibus tristique.

Phasellus efficitur venenatis nunc quis condimentum. Integer consequat tincidunt urna, non congue augue maximus nec. Proin eget risus leo. Sed at magna erat. Duis non purus ac ligula tristique ultricies. Maecenas vitae mattis dolor, ac venenatis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce pretium interdum elit non aliquet. Phasellus leo arcu, iaculis vel dolor non, finibus tincidunt libero. Maecenas elementum pharetra leo eget ornare. Nunc ut ornare nisi. Cras id auctor diam. Aliquam malesuada lorem odio, sed vehicula nibh imperdiet sit amet.

Maecenas dictum sit amet sapien a tincidunt. In pharetra urna eu enim bibendum semper. Fusce aliquam nulla quis dui pretium aliquet. Curabitur a volutpat purus. Sed blandit interdum erat. Duis pharetra hendrerit tempus. Nam ac ex et nulla consectetur imperdiet. Vestibulum sed aliquet ex, posuere egestas felis. Proin sollicitudin euismod elit in vulputate. Praesent et augue nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
"""
